background #151218
foreground #e7e0e8
selection_background #4c4357
selection_foreground #eadef7
url_color #f1b7c3
cursor #e7e0e8
cursor_text_color #151218

# Tabs
active_tab_background #d5bbfc
active_tab_foreground #3a255b
inactive_tab_background #1d1a20
inactive_tab_foreground #cbc4cf

# Windows
active_border_color #d5bbfc
inactive_border_color #49454e

# Standard ANSI Terminal Colors
color0 #151218
color1 #ffb4ab
color2 #d5bbfc
color3 #f1b7c3
color4 #cec2db
color5 #513c73
color6 #643b44
color7 #e7e0e8

color8 #958e99
color9 #93000a
color10 #d5bbfc
color11 #f1b7c3
color12 #cec2db
color13 #513c73
color14 #643b44
color15 #cbc4cf

# Custom Palette 
color16 #f1b7c3
color17 #d5bbfc
color18 #cec2db
color19 #643b44
color20 #958e99
color21 #e7e0e8
