[config]
version = "4.2.0"

[templates.hyprland]
input_path = "~/.config/matugen/templates/colors.lua"
output_path = "~/.config/hypr/colors/colors.lua"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "kitty @ set-colors -a ~/.config/kitty/colors.conf &"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk3.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk4.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.qt5]
input_path = "~/.config/matugen/templates/qt.conf"
output_path = "~/.config/qt5ct/colors/colors.conf"

[templates.qt6]
input_path = "~/.config/matugen/templates/qt.conf"
output_path = "~/.config/qt6ct/colors/colors.conf"

[templates.kde]
input_path = "~/.config/matugen/templates/kde.colors"
output_path = "~/.local/share/color-schemes/colors.colors"

[templates.zsh]
input_path = "~/.config/matugen/templates/zsh.zsh"
output_path = "~/.config/zsh/colors.zsh"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/colors.theme"

[templates.cava]
input_path = "~/.config/matugen/templates/cava-config"
output_path = "~/.config/cava/config"
post_hook = "pkill -USR1 -x cava &"

[templates.quickshell]
input_path = "~/.config/matugen/templates/Colors.qml"
output_path = "~/.config/quickshell/Colors.qml"

[templates.vesktop]
input_path = "~/.config/matugen/templates/vesktop.css"
output_path = "~/.config/vesktop/settings/quickCss.css"

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/colors/colors.conf'
