$bg_dim      = rgba(211e2499)
$text_main   = rgba(e7e0e8ff)
$text_sub    = rgba(cbc4cfaa)
$accent_blue = rgba(d5bbfcff)
$user_text   = rgba(e7e0e8b3)

$pill_bg     = rgba(0, 0, 0, 0.0)

$success_clr = rgba(cec2dbff)
$fail_clr    = rgba(ffb4abff)
$battery_clr = rgba(cbc4cf66)
