theme[main_bg]="#151218"
theme[main_fg]="#e7e0e8"

theme[title]="#d5bbfc"
theme[hi_fg]="#d5bbfc"
theme[selected_bg]="#2c292f"
theme[selected_fg]="#e7e0e8"

theme[inactive_fg]="#958e99"

theme[graph_text]="#cbc4cf"
theme[graph_line]="#d5bbfc"

theme[cpu_box]="#f1b7c3"
theme[mem_box]="#d5bbfc"
theme[net_box]="#cec2db"
theme[proc_box]="#ffb4ab"

theme[meter_bg]="#2c292f"
theme[meter_fg]="#d5bbfc"

theme[process_start]="#cec2db"
theme[process_mid]="#d5bbfc"
theme[process_end]="#f1b7c3"
