theme[main_bg]="{{colors.surface.default.hex}}"
theme[main_fg]="{{colors.on_surface.default.hex}}"

theme[title]="{{colors.primary.default.hex}}"
theme[hi_fg]="{{colors.primary.default.hex}}"
theme[selected_bg]="{{colors.surface_container_high.default.hex}}"
theme[selected_fg]="{{colors.on_surface.default.hex}}"

theme[inactive_fg]="{{colors.outline.default.hex}}"

theme[graph_text]="{{colors.on_surface_variant.default.hex}}"
theme[graph_line]="{{colors.primary.default.hex}}"

theme[cpu_box]="{{colors.tertiary.default.hex}}"
theme[mem_box]="{{colors.primary.default.hex}}"
theme[net_box]="{{colors.secondary.default.hex}}"
theme[proc_box]="{{colors.error.default.hex}}"

theme[meter_bg]="{{colors.surface_container_high.default.hex}}"
theme[meter_fg]="{{colors.primary.default.hex}}"

theme[process_start]="{{colors.secondary.default.hex}}"
theme[process_mid]="{{colors.primary.default.hex}}"
theme[process_end]="{{colors.tertiary.default.hex}}"
